version: '3.9'
volumes:
  next:
services:
  memonium:
    build:
      context: ./app
    tty: true
    container_name: front
    ports:
      - 3000:3000
    volumes:
      - ./app:/works
      - next:/works/.next