version: '3.9'
volumes:
  node_modules:
services:
  memonium:
    build:
      context: ./app
    tty: true
    container_name: front
    ports:
      - 3000:3000
    volumes:
      - ./app:/works
      - node_modules:/works/node_modules